services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      MOTD: "Vanilla Minecraft, Chill Vibes Only"
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
      restart: always
    volumes:
    - ${HOME}/data/minecraft:/data
